name: PayHub API Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run PayHub Tests
        # We are using the exact folder path from your sidebar
        run: |
          newman run "./postman/PayHub REST API.postman_collection.json" \
          -e "./postman/PayHub-Dev.postman_environment.json" \
          -r cli,htmlextra --reporter-htmlextra-export reports/payhub-report.html

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: PayHub-Test-Report
          path: reports/