name: PayHub API Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Create Reports Directory
        run: mkdir -p reports

      - name: Run PayHub Dev Tests
        # Note: Added 'postman/' prefix to match your folder structure
        run: |
          newman run postman/PayHub\ REST\ API.postman_collection.json \
          -e postman/PayHub-Dev.postman_environment.json \
          -r cli,htmlextra --reporter-htmlextra-export reports/dev-report.html

      - name: Upload Reports to GitHub
        if: always() # Uploads even if the tests fail so you can see why!
        uses: actions/upload-artifact@v3
        with:
          name: PayHub-Test-Reports
          path: reports/